name: Build and Deploy to Nexus

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Setup Maven settings.xml
      if: github.event_name != 'pull_request'
      uses: s4u/maven-settings-action@v2.8.0
      with:
        servers: |
          [{
            "id": "nexus",
            "username": "${{ secrets.NEXUS_USERNAME }}",
            "password": "${{ secrets.NEXUS_PASSWORD }}"
          }]

    - name: Deploy to Nexus
      if: github.event_name != 'pull_request'
      run: mvn deploy -DskipTests
      env:
        NEXUS_URL: ${{ secrets.NEXUS_URL }}
